project_id = "zjxikfcjatjzbhkzciji"

[functions.ai-report-insights]
verify_jwt = false

[functions.parse-mls-input]
verify_jwt = false

[functions.report-notifications]
verify_jwt = false

[functions.send-emails]
verify_jwt = false
