import { useState, useCallback, useRef } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { toast } from '@/hooks/use-toast';
import { Loader2, Copy, Check, BarChart3, Info, TrendingUp, Clock, DollarSign, Share2 } from 'lucide-react';
import { cn } from '@/lib/utils';

const PROPERTY_TYPES = ['Single Family', 'Condo', 'Townhome', 'Multi-Family'] as const;

async function fetchAddressSuggestions(query: string): Promise<string[]> {
  if (query.length < 5) return [];
  try {
    const parts = query.split(',').map((s: string) => s.trim());
    const params = new URLSearchParams({ street: parts[0] || '', city: parts[1] || '', state: parts[2] || '', benchmark: 'Public_AR_Current', format: 'json' });
    const res = await fetch(`https://geocoding.geo.census.gov/geocoder/locations/address?${params}`);
    if (!res.ok) return [];
    const data = await res.json();
    return (data?.result?.addressMatches || []).slice(0, 5).map((m: any) => m.matchedAddress as string);
  } catch { return []; }
}

function stripMarkdown(text: string): string {
  return text.replace(/^#{1,6}\s+/gm, '').replace(/\*\*([^*]+)\*\*/g, '$1').replace(/\*([^*]+)\*/g, '$1').replace(/^[-*]\s+/gm, '• ').replace(/\n{3,}/g, '\n\n').trim();
}

interface CMASection { title: string; content: string; icon: React.ElementType; highlight?: boolean; }

function parseCMAOutput(raw: string): CMASection[] {
  const cleaned = stripMarkdown(raw);
  const sections: CMASection[] = [];
  const valueMatch = cleaned.match(/estimated\s*market\s*value[:\s]*([^\n]+(?:\n(?![•\d])[^\n]+)*)/i);
  const priceMatch = cleaned.match(/suggested\s*list\s*price[:\s]*([^\n]+(?:\n(?![•\d])[^\n]+)*)/i);
  const domMatch = cleaned.match(/days\s*on\s*market[:\s]*([^\n]+(?:\n(?![•\d])[^\n]+)*)/i);
  const factorsMatch = cleaned.match(/key\s*pricing\s*factors?[:\s\n]*((?:[•\-][^\n]+\n?)+)/i);
  if (valueMatch) sections.push({ title: 'Estimated Market Value', content: valueMatch[1].trim(), icon: TrendingUp, highlight: true });
  if (priceMatch) sections.push({ title: 'Suggested List Price', content: priceMatch[1].trim(), icon: DollarSign, highlight: true });
  if (domMatch) sections.push({ title: 'Days on Market Estimate', content: domMatch[1].trim(), icon: Clock });
  if (factorsMatch) sections.push({ title: 'Key Pricing Factors', content: factorsMatch[1].trim(), icon: BarChart3 });
  if (sections.length === 0) {
    sections.push({ title: 'CMA Results', content: cleaned, icon: BarChart3, highlight: true });
  }
  return sections;
}

function DisclaimerPopover() {
  const [open, setOpen] = useState(false);
  return (
    <div className="relative inline-block">
      <button onClick={() => setOpen(o => !o)} className="flex items-center gap-1 text-[10px] text-muted-foreground hover:text-foreground transition-colors">
        <Info className="h-3 w-3" /><span>Disclaimer</span>
      </button>
      {open && (
        <>
          <div className="fixed inset-0 z-40" onClick={() => setOpen(false)} />
          <div className="absolute bottom-full right-0 mb-2 w-72 bg-card border border-border rounded-xl p-3 shadow-xl z-50 text-xs text-muted-foreground leading-relaxed">
            This CMA is generated by AI for informational purposes only. It is not a licensed appraisal or formal valuation. Actual market value depends on property condition, local MLS data, and other factors. Consult a licensed appraiser and review recent comparable sales before making pricing decisions.
          </div>
        </>
      )}
    </div>
  );
}

export default function QuickCMA() {
  const [address, setAddress] = useState('');
  const [suggestions, setSuggestions] = useState<string[]>([]);
  const [showSuggestions, setShowSuggestions] = useState(false);
  const [suggestionsLoading, setSuggestionsLoading] = useState(false);
  const [beds, setBeds] = useState(3);
  const [baths, setBaths] = useState(2);
  const [sqft, setSqft] = useState('');
  const [propertyType, setPropertyType] = useState<string>('Single Family');
  const [targetPrice, setTargetPrice] = useState('');
  const [loading, setLoading] = useState(false);
  const [sections, setSections] = useState<CMASection[]>([]);
  const [rawReport, setRawReport] = useState('');
  const [copied, setCopied] = useState(false);
  const debounceRef = useRef<ReturnType<typeof setTimeout>>();

  const handleAddressChange = useCallback((val: string) => {
    setAddress(val);
    setSuggestions([]);
    clearTimeout(debounceRef.current);
    if (val.includes(',') && val.length > 8) {
      setSuggestionsLoading(true);
      debounceRef.current = setTimeout(async () => {
        const results = await fetchAddressSuggestions(val);
        setSuggestions(results);
        setShowSuggestions(results.length > 0);
        setSuggestionsLoading(false);
      }, 450);
    }
  }, []);

  const runCMA = async () => {
    if (!address.trim() || !sqft.trim()) {
      toast({ title: 'Missing fields', description: 'Address and square footage are required.', variant: 'destructive' });
      return;
    }
    setLoading(true); setSections([]); setRawReport('');
    try {
      const res = await fetch('/api/claude', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          model: 'claude-sonnet-4-6',
          max_tokens: 900,
          system: 'You are a real estate pricing expert. Respond in plain text only — no markdown, no hashtags, no asterisks, no bold. Use plain sentences and bullet points starting with "•". Structure your response with these four clearly labeled sections:\n1. Estimated Market Value Range\n2. Key Pricing Factors (3 bullet points)\n3. Suggested List Price\n4. Days on Market Estimate',
          messages: [{ role: 'user', content: `CMA for: ${address.trim()}\n${beds} bed / ${baths} bath / ${sqft} sqft / ${propertyType}${targetPrice.trim() ? `\nTarget price: ${targetPrice.trim()}` : ''}\n\nProvide specific dollar ranges and brief rationale for each section.` }],
        }),
      });
      if (!res.ok) throw new Error(`API error ${res.status}`);
      const data = await res.json();
      if (data?.type === 'error') throw new Error(data?.error?.message || 'Could not generate response.');
      const text = data.content?.[0]?.text || 'No response received.';
      setRawReport(text);
      setSections(parseCMAOutput(text));
    } catch (e: any) {
      toast({ title: 'Error', description: e.message, variant: 'destructive' });
    } finally { setLoading(false); }
  };

  const copyReport = async () => {
    await navigator.clipboard.writeText(`Quick CMA — ${address}\n${beds}bd/${baths}ba · ${sqft}sqft · ${propertyType}\n${new Date().toLocaleDateString()}\n\n${rawReport}\n\n— Market Compass`);
    setCopied(true);
    toast({ title: 'Copied to clipboard' });
    setTimeout(() => setCopied(false), 2000);
  };

  const shareReport = () => {
    const text = `CMA for ${address}\n${beds}bd/${baths}ba ${sqft}sqft\n\n${rawReport}\n\n— Market Compass`;
    if (navigator.share) { navigator.share({ text }).catch(() => {}); } else { window.open(`sms:?body=${encodeURIComponent(text)}`); }
  };

  return (
    <div className="min-h-screen bg-background px-4 py-8 max-w-2xl mx-auto space-y-5 pb-24">
      <div className="flex items-center gap-3">
        <BarChart3 className="h-6 w-6 text-primary shrink-0" />
        <div>
          <h1 className="text-xl font-bold text-foreground">Quick CMA</h1>
          <p className="text-xs text-muted-foreground">AI-powered Comparative Market Analysis</p>
        </div>
      </div>

      <Card>
        <CardContent className="pt-5 space-y-4">
          <div className="relative">
            <Label className="text-xs font-medium text-muted-foreground mb-1.5 block">Subject Property Address *</Label>
            <div className="relative">
              <Input value={address} onChange={e => handleAddressChange(e.target.value)} onFocus={() => suggestions.length > 0 && setShowSuggestions(true)} onBlur={() => setTimeout(() => setShowSuggestions(false), 150)} placeholder="123 Main St, Springfield, IL" className="pr-8" />
              {suggestionsLoading && <Loader2 className="absolute right-2.5 top-1/2 -translate-y-1/2 h-3.5 w-3.5 animate-spin text-muted-foreground" />}
            </div>
            <p className="text-[10px] text-muted-foreground mt-1">Type street, city, state for address suggestions</p>
            {showSuggestions && suggestions.length > 0 && (
              <div className="absolute z-20 top-full mt-1 w-full bg-card border border-border rounded-lg shadow-lg overflow-hidden">
                {suggestions.map((s, i) => (
                  <button key={i} className="w-full text-left px-3 py-2 text-sm hover:bg-muted/60 transition-colors border-b border-border/50 last:border-0" onMouseDown={() => { setAddress(s); setSuggestions([]); setShowSuggestions(false); }}>{s}</button>
                ))}
              </div>
            )}
          </div>

          <div className="grid grid-cols-3 gap-3">
            {[['Beds', beds, (v: number) => setBeds(v), 1, undefined], ['Baths', baths, (v: number) => setBaths(v), 0.5, undefined], ['Sq Ft *', sqft, (v: string) => setSqft(v), undefined, '1800']].map(([label, val, setter, step, placeholder], i) => (
              <div key={i}>
                <Label className="text-xs font-medium text-muted-foreground mb-1.5 block">{label as string}</Label>
                <Input type="number" min={0} step={step as number || 1} value={val as string | number} onChange={e => (setter as Function)(i < 2 ? +e.target.value : e.target.value)} placeholder={placeholder as string || ''} />
              </div>
            ))}
          </div>

          <div>
            <Label className="text-xs font-medium text-muted-foreground mb-1.5 block">Property Type</Label>
            <div className="flex flex-wrap gap-2">
              {PROPERTY_TYPES.map(t => (
                <button key={t} onClick={() => setPropertyType(t)} className={cn('px-3 py-1.5 rounded-full text-xs font-medium transition-colors border', propertyType === t ? 'bg-primary text-primary-foreground border-primary' : 'bg-background text-muted-foreground border-border hover:border-primary/40')}>{t}</button>
              ))}
            </div>
          </div>

          <div>
            <Label className="text-xs font-medium text-muted-foreground mb-1.5 block">Target List Price (optional)</Label>
            <Input value={targetPrice} onChange={e => setTargetPrice(e.target.value)} placeholder="$425,000" />
          </div>

          <Button onClick={runCMA} disabled={loading} className="w-full">
            {loading ? <><Loader2 className="h-4 w-4 mr-2 animate-spin" />Analyzing…</> : 'Run CMA Analysis'}
          </Button>
        </CardContent>
      </Card>

      {sections.length > 0 && (
        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <p className="text-xs text-muted-foreground">{address} · {beds}bd/{baths}ba · {sqft}sqft · {new Date().toLocaleDateString()}</p>
            <DisclaimerPopover />
          </div>
          {sections.map((sec, i) => {
            const Icon = sec.icon;
            return (
              <Card key={i} className={cn(sec.highlight && 'border-primary/30 bg-primary/5')}>
                <CardContent className="pt-4 pb-4">
                  <div className="flex items-center gap-2 mb-2">
                    <div className={cn('h-7 w-7 rounded-lg flex items-center justify-center shrink-0', sec.highlight ? 'bg-primary/15' : 'bg-muted')}>
                      <Icon className={cn('h-4 w-4', sec.highlight ? 'text-primary' : 'text-muted-foreground')} />
                    </div>
                    <p className="text-sm font-semibold">{sec.title}</p>
                  </div>
                  <p className="text-sm text-foreground leading-relaxed whitespace-pre-wrap pl-9">{sec.content}</p>
                </CardContent>
              </Card>
            );
          })}
          <div className="flex gap-2">
            <Button onClick={copyReport} variant="outline" className="flex-1 gap-2">{copied ? <><Check className="h-4 w-4" />Copied</> : <><Copy className="h-4 w-4" />Copy CMA</>}</Button>
            <Button onClick={shareReport} variant="outline" className="flex-1 gap-2"><Share2 className="h-4 w-4" />Share</Button>
          </div>
        </div>
      )}
    </div>
  );
}
